name: OpenBikeSensor - CI
on: [pull_request, push]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
       image: infinitecoding/platformio-for-ci:latest
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Prepare output directories
      run: mkdir bin

    - name: Build firmware
      run: platformio ci --build-dir="./bin" --keep-build-dir --project-conf=platformio.ini ./OpenBikeSensorFirmware/
